name: dreg_prep
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::cutadapt
  - bioconda::fastx_toolkit
  - bioconda::seqtk
  # NOTE Technically the script says 0.20.2, I installed 0.20.4
  # - prinseq-lite.pl Just manually copied it. Couldn't tell if prinseq == prinseq-lite
  - bioconda::bwa
  - bioconda::samtools=1.9
  - bioconda::bedtools>=2.28.0
  - bioconda::ucsc-bedgraphtobigwig
  - bioconda::bedops