name: dreg_prep
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::cutadapt
  - bioconda::fastx_toolkit
  - bioconda::seqtk
  - bioconda::prinseq # FIXME =0.20.2
  - bioconda::bwa
  - bioconda::samtools
  - bioconda::bedtools>=2.28.0
  - bioconda::ucsc-bedgraphtobigwig
  - bioconda::bedops
