[project]
authors = ["Edmund Miller <git@edmundmiller.dev>", "eternal-flame-AD <yume@yumechi.jp>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "dREG-nf"
platforms = ["linux-64"]
version = "0.1.0"

[tasks."build_multi_align"]
cmd = [
    "cargo",
    "build",
    "--release",
    "--manifest-path",
    "crates/multi_align/Cargo.toml",
]

[tasks."run_dbnascent"]
cwd = "dbnascent"
cmd = [
    "nextflow",
    "run",
    "../main.nf",
    "--run_dreg",
]

[dependencies]
bbmap = ">=39.10,<40"
fastqc = ">=0.12.1,<0.13"
hisat2 = ">=2.2.1,<3"
samtools = ">=1.21,<2"
preseq = ">=2.0.2,<3"
igvtools = ">=2.17.3,<3"
mpich = ">=4.2.3,<5"
bedtools = ">=2.31.1,<3"
sra-tools = ">=2.9.6,<3"
nextflow = ">=24.4.4,<25"
ucsc-bedgraphtobigwig = ">=469,<470"
bwa = ">=0.7.18,<0.8"
bowtie2 = ">=2.5.4,<3"